services:
  api:
    build: .
    container_name: real_estate_api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/model_artifacts/lightgbm_model.txt
    volumes:
      - ./src/main.py:/app/main.py
      - ./src/schemas.py:/app/schemas.py
      - ./model_artifacts:/app/model_artifacts
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    
  trainer:
    build:
      context: .
      dockerfile: trainer.Dockerfile
    container_name: model_trainer_tool
    volumes:
      - ./model_artifacts:/trainer_app
      - ./chotot_bds_video_data.csv:/trainer_app/chotot_bds_video_data.csv

  predictor:
    container_name: bds_predictor
    build:
      context: .
      dockerfile: predictor.Dockerfile
    volumes:
      - ./model_artifacts:/app/model_artifacts:ro
      - ./model_artifacts/test_predict.py:/app/test_predict.py