name = "admin"
compatibility_date = "2025-11-06"
pages_build_output_dir = "out"

# SPA routing - redirect all routes to index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[vars]
ENVIRONMENT = "production"
AUTH_GUI_URL = "https://auth.vpbank.workers.dev"
AUTH_API_URL = "https://auth.vpbank.workers.dev"
API_URL= "https://api.vpbank.workers.dev"

[dev.vars]
ENVIRONMENT = "development"
AUTH_GUI_URL = "http://localhost:8787"
AUTH_API_URL = "http://localhost:8787"
API_URL= "http://localhost:3004"

[[app_cache]]
binding = "app_cache"
id = "e12207eca0bb41d6b801beef00fddfe5" # You need to replace this with your actual KV namespace ID
preview_id = "e12207eca0bb41d6b801beef00fddfe5" # You need to replace this with your actual preview KV namespace ID
